// Central place listing every machine-readable error "code" used in the API.
// Keeping them here avoids typos and duplicated magic strings across files.

module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MISSING_PARAMETER: "MISSING_PARAMETER",
  INVALID_PARAMETER: "INVALID_PARAMETER",
  PHONE_NOT_FOUND: "PHONE_NOT_FOUND",
  BRAND_NOT_FOUND: "BRAND_NOT_FOUND",
  INVALID_PHONE_IDS: "INVALID_PHONE_IDS",
  TOO_MANY_COMPARE_IDS: "TOO_MANY_COMPARE_IDS",
  NOT_ENOUGH_COMPARE_IDS: "NOT_ENOUGH_COMPARE_IDS",
  DUPLICATE_SLUG: "DUPLICATE_SLUG",
  UNAUTHORIZED: "UNAUTHORIZED",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
