// Prisma seed script.
// Run with: npm run seed   (or: node prisma/seed.js)
//
// NOTE: Specs below are approximate/representative sample data for
// development and testing only — they are NOT guaranteed to be
// officially verified manufacturer specifications. Treat them as
// placeholder data to exercise the API and frontend.

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const phones = [
  {
    brand: "Apple",
    model: "iPhone 16 Pro",
    slug: "apple-iphone-16-pro",
    price: 999.0,
    releaseDate: new Date("2024-09-20"),
    description: "Apple's flagship with a titanium frame and the A18 Pro chip.",
    imageUrl: "https://example.com/images/iphone-16-pro.jpg",
    displaySize: 6.3,
    displayType: "LTPO OLED",
    resolution: "1206 x 2622",
    refreshRate: 120,
    processor: "Apple A18 Pro",
    gpu: "Apple GPU (6-core)",
    ram: 8,
    storage: 256,
    operatingSystem: "iOS 18",
    mainCamera: "48MP, f/1.78",
    ultrawideCamera: "48MP, f/2.2",
    telephotoCamera: "12MP, f/2.8, 5x optical",
    frontCamera: "12MP, f/1.9",
    videoRecording: "4K@120fps",
    batteryCapacity: 3582,
    chargingSpeed: "27W wired, 25W MagSafe",
    wirelessCharging: true,
    network: "GSM / CDMA / HSPA / LTE / 5G",
    wifi: "Wi-Fi 7",
    bluetooth: "5.3",
    nfc: true,
    usb: "USB Type-C 3.0",
    fiveG: true,
    dimensions: "149.6 x 71.5 x 8.25 mm",
    weight: 199,
    rating: 4.7,
  },
  {
    brand: "Apple",
    model: "iPhone 15",
    slug: "apple-iphone-15",
    price: 699.0,
    releaseDate: new Date("2023-09-22"),
    description: "A well-rounded iPhone with USB-C and the A16 Bionic chip.",
    imageUrl: "https://example.com/images/iphone-15.jpg",
    displaySize: 6.1,
    displayType: "OLED",
    resolution: "1179 x 2556",
    refreshRate: 60,
    processor: "Apple A16 Bionic",
    gpu: "Apple GPU (5-core)",
    ram: 6,
    storage: 128,
    operatingSystem: "iOS 17",
    mainCamera: "48MP, f/1.6",
    ultrawideCamera: "12MP, f/2.4",
    telephotoCamera: null,
    frontCamera: "12MP, f/1.9",
    videoRecording: "4K@60fps",
    batteryCapacity: 3349,
    chargingSpeed: "20W wired, 15W MagSafe",
    wirelessCharging: true,
    network: "GSM / CDMA / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6",
    bluetooth: "5.3",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "147.6 x 71.6 x 7.8 mm",
    weight: 171,
    rating: 4.5,
  },
  {
    brand: "Samsung",
    model: "Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    price: 1299.0,
    releaseDate: new Date("2025-01-22"),
    description: "Samsung's top-tier Ultra model with S Pen support and a 200MP camera.",
    imageUrl: "https://example.com/images/galaxy-s25-ultra.jpg",
    displaySize: 6.9,
    displayType: "Dynamic LTPO AMOLED 2X",
    resolution: "1440 x 3120",
    refreshRate: 120,
    processor: "Snapdragon 8 Elite for Galaxy",
    gpu: "Adreno 830",
    ram: 12,
    storage: 256,
    operatingSystem: "Android 15 (One UI 7)",
    mainCamera: "200MP, f/1.7",
    ultrawideCamera: "50MP, f/1.9",
    telephotoCamera: "50MP, f/3.4, 5x optical",
    frontCamera: "12MP, f/2.2",
    videoRecording: "8K@30fps",
    batteryCapacity: 5000,
    chargingSpeed: "45W wired, 15W wireless",
    wirelessCharging: true,
    network: "GSM / CDMA / HSPA / LTE / 5G",
    wifi: "Wi-Fi 7",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 3.2",
    fiveG: true,
    dimensions: "162.8 x 77.6 x 8.2 mm",
    weight: 218,
    rating: 4.8,
  },
  {
    brand: "Samsung",
    model: "Galaxy A55",
    slug: "samsung-galaxy-a55",
    price: 449.0,
    releaseDate: new Date("2024-03-11"),
    description: "Mid-range Galaxy A-series phone with a durable Gorilla Glass Victus+ front.",
    imageUrl: "https://example.com/images/galaxy-a55.jpg",
    displaySize: 6.6,
    displayType: "Super AMOLED",
    resolution: "1080 x 2340",
    refreshRate: 120,
    processor: "Exynos 1480",
    gpu: "Xclipse 530",
    ram: 8,
    storage: 128,
    operatingSystem: "Android 14 (One UI 6.1)",
    mainCamera: "50MP, f/1.8",
    ultrawideCamera: "12MP, f/2.2",
    telephotoCamera: null,
    frontCamera: "32MP, f/2.2",
    videoRecording: "4K@30fps",
    batteryCapacity: 5000,
    chargingSpeed: "25W wired",
    wirelessCharging: false,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 5",
    bluetooth: "5.3",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "161.1 x 77.4 x 8.2 mm",
    weight: 213,
    rating: 4.3,
  },
  {
    brand: "OnePlus",
    model: "OnePlus 13",
    slug: "oneplus-13",
    price: 899.0,
    releaseDate: new Date("2025-01-07"),
    description: "Flagship-grade OnePlus with Snapdragon 8 Elite and fast Hasselblad cameras.",
    imageUrl: "https://example.com/images/oneplus-13.jpg",
    displaySize: 6.82,
    displayType: "LTPO AMOLED",
    resolution: "1440 x 3168",
    refreshRate: 120,
    processor: "Snapdragon 8 Elite",
    gpu: "Adreno 830",
    ram: 12,
    storage: 256,
    operatingSystem: "Android 15 (OxygenOS 15)",
    mainCamera: "50MP, f/1.6",
    ultrawideCamera: "50MP, f/2.0",
    telephotoCamera: "50MP, f/2.6, 3x optical",
    frontCamera: "32MP, f/2.4",
    videoRecording: "4K@60fps",
    batteryCapacity: 6000,
    chargingSpeed: "80W wired, 50W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 7",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 3.2",
    fiveG: true,
    dimensions: "162.9 x 76.6 x 8.5 mm",
    weight: 210,
    rating: 4.6,
  },
  {
    brand: "OnePlus",
    model: "OnePlus Nord 4",
    slug: "oneplus-nord-4",
    price: 449.0,
    releaseDate: new Date("2024-07-16"),
    description: "A metal-unibody mid-ranger with clean software and fast charging.",
    imageUrl: "https://example.com/images/oneplus-nord-4.jpg",
    displaySize: 6.74,
    displayType: "AMOLED",
    resolution: "1240 x 2772",
    refreshRate: 120,
    processor: "Snapdragon 7+ Gen 3",
    gpu: "Adreno 720",
    ram: 8,
    storage: 128,
    operatingSystem: "Android 14 (OxygenOS 14.1)",
    mainCamera: "50MP, f/1.88",
    ultrawideCamera: "8MP, f/2.2",
    telephotoCamera: null,
    frontCamera: "16MP, f/2.4",
    videoRecording: "4K@30fps",
    batteryCapacity: 5500,
    chargingSpeed: "100W wired",
    wirelessCharging: false,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "162.9 x 75.3 x 7.99 mm",
    weight: 199,
    rating: 4.4,
  },
  {
    brand: "Google",
    model: "Pixel 9 Pro",
    slug: "google-pixel-9-pro",
    price: 999.0,
    releaseDate: new Date("2024-08-22"),
    description: "Google's AI-forward flagship running stock Android with the Tensor G4.",
    imageUrl: "https://example.com/images/pixel-9-pro.jpg",
    displaySize: 6.3,
    displayType: "LTPO OLED",
    resolution: "1280 x 2856",
    refreshRate: 120,
    processor: "Google Tensor G4",
    gpu: "Mali-G715 MC7",
    ram: 16,
    storage: 128,
    operatingSystem: "Android 14",
    mainCamera: "50MP, f/1.68",
    ultrawideCamera: "48MP, f/1.7",
    telephotoCamera: "48MP, f/2.8, 5x optical",
    frontCamera: "42MP, f/2.2",
    videoRecording: "4K@60fps",
    batteryCapacity: 4700,
    chargingSpeed: "27W wired, 23W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 7",
    bluetooth: "5.3",
    nfc: true,
    usb: "USB Type-C 3.2",
    fiveG: true,
    dimensions: "152.8 x 72.0 x 8.5 mm",
    weight: 199,
    rating: 4.6,
  },
  {
    brand: "Google",
    model: "Pixel 8a",
    slug: "google-pixel-8a",
    price: 499.0,
    releaseDate: new Date("2024-05-14"),
    description: "The budget-friendly Pixel with flagship-level Tensor G3 performance.",
    imageUrl: "https://example.com/images/pixel-8a.jpg",
    displaySize: 6.1,
    displayType: "OLED",
    resolution: "1080 x 2400",
    refreshRate: 120,
    processor: "Google Tensor G3",
    gpu: "Mali-G715 MC7",
    ram: 8,
    storage: 128,
    operatingSystem: "Android 14",
    mainCamera: "64MP, f/1.89",
    ultrawideCamera: "13MP, f/2.2",
    telephotoCamera: null,
    frontCamera: "13MP, f/2.2",
    videoRecording: "4K@60fps",
    batteryCapacity: 4492,
    chargingSpeed: "18W wired, 7.5W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    nfc: true,
    usb: "USB Type-C 3.2",
    fiveG: true,
    dimensions: "152.1 x 72.7 x 8.9 mm",
    weight: 188,
    rating: 4.5,
  },
  {
    brand: "Xiaomi",
    model: "Xiaomi 14 Ultra",
    slug: "xiaomi-14-ultra",
    price: 1099.0,
    releaseDate: new Date("2024-02-25"),
    description: "Photography-focused flagship co-engineered with Leica optics.",
    imageUrl: "https://example.com/images/xiaomi-14-ultra.jpg",
    displaySize: 6.73,
    displayType: "LTPO AMOLED",
    resolution: "1440 x 3200",
    refreshRate: 120,
    processor: "Snapdragon 8 Gen 3",
    gpu: "Adreno 750",
    ram: 16,
    storage: 512,
    operatingSystem: "Android 14 (HyperOS)",
    mainCamera: "50MP, f/1.63-4.0 (variable aperture)",
    ultrawideCamera: "50MP, f/1.8",
    telephotoCamera: "50MP, f/3.0, 5x periscope",
    frontCamera: "32MP, f/2.0",
    videoRecording: "8K@24fps",
    batteryCapacity: 5300,
    chargingSpeed: "90W wired, 80W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 7",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 3.2",
    fiveG: true,
    dimensions: "161.4 x 75.3 x 9.2 mm",
    weight: 224,
    rating: 4.6,
  },
  {
    brand: "Xiaomi",
    model: "Xiaomi 14T",
    slug: "xiaomi-14t",
    price: 649.0,
    releaseDate: new Date("2024-09-26"),
    description: "Well-rounded mid-flagship with a 144Hz display and 67W charging.",
    imageUrl: "https://example.com/images/xiaomi-14t.jpg",
    displaySize: 6.67,
    displayType: "AMOLED",
    resolution: "1220 x 2712",
    refreshRate: 144,
    processor: "MediaTek Dimensity 8300 Ultra",
    gpu: "Mali-G615 MC6",
    ram: 12,
    storage: 256,
    operatingSystem: "Android 14 (HyperOS)",
    mainCamera: "50MP, f/1.7",
    ultrawideCamera: "12MP, f/2.2",
    telephotoCamera: "50MP, f/1.9, 2x optical",
    frontCamera: "20MP, f/2.2",
    videoRecording: "4K@30fps",
    batteryCapacity: 5000,
    chargingSpeed: "67W wired",
    wirelessCharging: false,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "160.4 x 75.1 x 7.8 mm",
    weight: 195,
    rating: 4.4,
  },
  {
    brand: "Redmi",
    model: "Redmi Note 14 Pro+",
    slug: "redmi-note-14-pro-plus",
    price: 399.0,
    releaseDate: new Date("2024-10-15"),
    description: "Feature-packed budget flagship with a curved AMOLED display.",
    imageUrl: "https://example.com/images/redmi-note-14-pro-plus.jpg",
    displaySize: 6.67,
    displayType: "Curved AMOLED",
    resolution: "1220 x 2712",
    refreshRate: 120,
    processor: "MediaTek Dimensity 7300 Ultra",
    gpu: "Mali-G615 MC2",
    ram: 8,
    storage: 256,
    operatingSystem: "Android 14 (HyperOS)",
    mainCamera: "200MP, f/1.65",
    ultrawideCamera: "8MP, f/2.2",
    telephotoCamera: null,
    frontCamera: "20MP, f/2.2",
    videoRecording: "4K@30fps",
    batteryCapacity: 5110,
    chargingSpeed: "120W wired, 50W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "161.2 x 74.2 x 8.0 mm",
    weight: 202,
    rating: 4.3,
  },
  {
    brand: "Redmi",
    model: "Redmi 13C",
    slug: "redmi-13c",
    price: 149.0,
    releaseDate: new Date("2023-11-10"),
    description: "Entry-level phone aimed at first-time smartphone buyers.",
    imageUrl: "https://example.com/images/redmi-13c.jpg",
    displaySize: 6.74,
    displayType: "IPS LCD",
    resolution: "720 x 1600",
    refreshRate: 90,
    processor: "MediaTek Helio G85",
    gpu: "Mali-G52 MC2",
    ram: 4,
    storage: 128,
    operatingSystem: "Android 13",
    mainCamera: "50MP, f/1.8",
    ultrawideCamera: null,
    telephotoCamera: null,
    frontCamera: "8MP, f/2.0",
    videoRecording: "1080p@30fps",
    batteryCapacity: 5000,
    chargingSpeed: "18W wired",
    wirelessCharging: false,
    network: "GSM / HSPA / LTE",
    wifi: "Wi-Fi 5",
    bluetooth: "5.3",
    nfc: false,
    usb: "USB Type-C 2.0",
    fiveG: false,
    dimensions: "168.6 x 76.7 x 8.1 mm",
    weight: 192,
    rating: 3.9,
  },
  {
    brand: "POCO",
    model: "POCO F6 Pro",
    slug: "poco-f6-pro",
    price: 549.0,
    releaseDate: new Date("2024-04-23"),
    description: "Performance-focused flagship-killer with Snapdragon 8 Gen 2.",
    imageUrl: "https://example.com/images/poco-f6-pro.jpg",
    displaySize: 6.67,
    displayType: "AMOLED",
    resolution: "1220 x 2712",
    refreshRate: 120,
    processor: "Snapdragon 8 Gen 2",
    gpu: "Adreno 740",
    ram: 12,
    storage: 256,
    operatingSystem: "Android 14 (HyperOS)",
    mainCamera: "50MP, f/1.6",
    ultrawideCamera: "8MP, f/2.2",
    telephotoCamera: null,
    frontCamera: "16MP, f/2.5",
    videoRecording: "4K@30fps",
    batteryCapacity: 5000,
    chargingSpeed: "120W wired",
    wirelessCharging: false,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "161.3 x 75.0 x 8.8 mm",
    weight: 209,
    rating: 4.4,
  },
  {
    brand: "POCO",
    model: "POCO X6",
    slug: "poco-x6",
    price: 299.0,
    releaseDate: new Date("2024-01-11"),
    description: "Value mid-ranger with an AMOLED display and Dimensity chip.",
    imageUrl: "https://example.com/images/poco-x6.jpg",
    displaySize: 6.67,
    displayType: "AMOLED",
    resolution: "1220 x 2712",
    refreshRate: 120,
    processor: "MediaTek Dimensity 8300 Ultra",
    gpu: "Mali-G615 MC6",
    ram: 8,
    storage: 256,
    operatingSystem: "Android 14 (HyperOS)",
    mainCamera: "64MP, f/1.79",
    ultrawideCamera: "8MP, f/2.2",
    telephotoCamera: null,
    frontCamera: "16MP, f/2.4",
    videoRecording: "4K@30fps",
    batteryCapacity: 5100,
    chargingSpeed: "67W wired",
    wirelessCharging: false,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 5",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "161.7 x 74.8 x 7.9 mm",
    weight: 181,
    rating: 4.2,
  },
  {
    brand: "Nothing",
    model: "Nothing Phone (2a)",
    slug: "nothing-phone-2a",
    price: 349.0,
    releaseDate: new Date("2024-03-05"),
    description: "Distinctive transparent design with the signature Glyph Interface.",
    imageUrl: "https://example.com/images/nothing-phone-2a.jpg",
    displaySize: 6.7,
    displayType: "AMOLED",
    resolution: "1084 x 2412",
    refreshRate: 120,
    processor: "MediaTek Dimensity 7200 Pro",
    gpu: "Mali-G610 MC4",
    ram: 8,
    storage: 128,
    operatingSystem: "Android 14 (Nothing OS 2.5)",
    mainCamera: "50MP, f/1.88",
    ultrawideCamera: "50MP, f/2.2",
    telephotoCamera: null,
    frontCamera: "32MP, f/2.2",
    videoRecording: "4K@30fps",
    batteryCapacity: 5000,
    chargingSpeed: "45W wired",
    wirelessCharging: false,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 5",
    bluetooth: "5.3",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "161.7 x 76.3 x 8.0 mm",
    weight: 190,
    rating: 4.3,
  },
  {
    brand: "Motorola",
    model: "Motorola Edge 50 Pro",
    slug: "motorola-edge-50-pro",
    price: 599.0,
    releaseDate: new Date("2024-04-24"),
    description: "Curved-display Edge phone with fast 125W TurboPower charging.",
    imageUrl: "https://example.com/images/moto-edge-50-pro.jpg",
    displaySize: 6.7,
    displayType: "pOLED",
    resolution: "1220 x 2712",
    refreshRate: 144,
    processor: "Snapdragon 7 Gen 3",
    gpu: "Adreno 720",
    ram: 12,
    storage: 512,
    operatingSystem: "Android 14",
    mainCamera: "50MP, f/1.4",
    ultrawideCamera: "13MP, f/2.2",
    telephotoCamera: "10MP, f/2.0, 3x optical",
    frontCamera: "50MP, f/2.0",
    videoRecording: "4K@30fps",
    batteryCapacity: 4500,
    chargingSpeed: "125W wired, 50W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6E",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "160.5 x 72.0 x 8.2 mm",
    weight: 186,
    rating: 4.3,
  },
  {
    brand: "Realme",
    model: "Realme GT 6",
    slug: "realme-gt-6",
    price: 549.0,
    releaseDate: new Date("2024-05-31"),
    description: "Performance flagship with Snapdragon 8s Gen 3 and 120W charging.",
    imageUrl: "https://example.com/images/realme-gt-6.jpg",
    displaySize: 6.78,
    displayType: "LTPO AMOLED",
    resolution: "1264 x 2780",
    refreshRate: 120,
    processor: "Snapdragon 8s Gen 3",
    gpu: "Adreno 735",
    ram: 12,
    storage: 256,
    operatingSystem: "Android 14 (Realme UI 5.0)",
    mainCamera: "50MP, f/1.88",
    ultrawideCamera: "8MP, f/2.2",
    telephotoCamera: "50MP, f/2.65, 2.5x optical",
    frontCamera: "32MP, f/2.4",
    videoRecording: "4K@30fps",
    batteryCapacity: 5500,
    chargingSpeed: "120W wired",
    wirelessCharging: false,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "161.6 x 74.7 x 8.6 mm",
    weight: 199,
    rating: 4.4,
  },
  {
    brand: "OPPO",
    model: "OPPO Find X7 Ultra",
    slug: "oppo-find-x7-ultra",
    price: 1099.0,
    releaseDate: new Date("2024-01-08"),
    description: "Dual-periscope flagship with Hasselblad-tuned quad cameras.",
    imageUrl: "https://example.com/images/oppo-find-x7-ultra.jpg",
    displaySize: 6.82,
    displayType: "LTPO AMOLED",
    resolution: "1440 x 3168",
    refreshRate: 120,
    processor: "Snapdragon 8 Gen 3",
    gpu: "Adreno 750",
    ram: 16,
    storage: 512,
    operatingSystem: "Android 14 (ColorOS 14)",
    mainCamera: "50MP, f/1.8",
    ultrawideCamera: "50MP, f/2.0",
    telephotoCamera: "50MP, f/2.6, 3x + 50MP 6x periscope",
    frontCamera: "32MP, f/2.4",
    videoRecording: "4K@60fps",
    batteryCapacity: 5000,
    chargingSpeed: "100W wired, 50W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 7",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 3.2",
    fiveG: true,
    dimensions: "164.3 x 76.2 x 9.5 mm",
    weight: 221,
    rating: 4.6,
  },
  {
    brand: "Vivo",
    model: "Vivo X100 Pro",
    slug: "vivo-x100-pro",
    price: 899.0,
    releaseDate: new Date("2023-11-13"),
    description: "ZEISS-co-engineered camera flagship with a periscope telephoto lens.",
    imageUrl: "https://example.com/images/vivo-x100-pro.jpg",
    displaySize: 6.78,
    displayType: "LTPO AMOLED",
    resolution: "1260 x 2800",
    refreshRate: 120,
    processor: "MediaTek Dimensity 9300",
    gpu: "Mali-G720 Immortalis MC12",
    ram: 16,
    storage: 512,
    operatingSystem: "Android 14 (OriginOS 4)",
    mainCamera: "50MP, f/1.75",
    ultrawideCamera: "50MP, f/2.0",
    telephotoCamera: "50MP, f/2.5, 5x periscope",
    frontCamera: "32MP, f/2.0",
    videoRecording: "8K@30fps",
    batteryCapacity: 5400,
    chargingSpeed: "100W wired, 30W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "164.1 x 74.8 x 9.1 mm",
    weight: 221,
    rating: 4.5,
  },
  {
    brand: "iQOO",
    model: "iQOO 12",
    slug: "iqoo-12",
    price: 749.0,
    releaseDate: new Date("2023-12-12"),
    description: "Gaming-oriented flagship with Snapdragon 8 Gen 3 and a 144Hz display.",
    imageUrl: "https://example.com/images/iqoo-12.jpg",
    displaySize: 6.78,
    displayType: "LTPO AMOLED",
    resolution: "1260 x 2800",
    refreshRate: 144,
    processor: "Snapdragon 8 Gen 3",
    gpu: "Adreno 750",
    ram: 16,
    storage: 512,
    operatingSystem: "Android 14 (OriginOS 4)",
    mainCamera: "50MP, f/1.68",
    ultrawideCamera: "50MP, f/2.0",
    telephotoCamera: "64MP, f/2.57, 3x optical",
    frontCamera: "16MP, f/2.4",
    videoRecording: "8K@30fps",
    batteryCapacity: 5000,
    chargingSpeed: "120W wired, 50W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 7",
    bluetooth: "5.4",
    nfc: true,
    usb: "USB Type-C 2.0",
    fiveG: true,
    dimensions: "164.0 x 75.2 x 8.7 mm",
    weight: 199,
    rating: 4.5,
  },
  {
    brand: "Samsung",
    model: "Galaxy Z Flip6",
    slug: "samsung-galaxy-z-flip6",
    price: 1099.0,
    releaseDate: new Date("2024-07-24"),
    description: "Compact foldable clamshell with a larger cover screen than its predecessor.",
    imageUrl: "https://example.com/images/galaxy-z-flip6.jpg",
    displaySize: 6.7,
    displayType: "Foldable Dynamic AMOLED 2X",
    resolution: "1080 x 2640",
    refreshRate: 120,
    processor: "Snapdragon 8 Gen 3 for Galaxy",
    gpu: "Adreno 750",
    ram: 12,
    storage: 256,
    operatingSystem: "Android 14 (One UI 6.1.1)",
    mainCamera: "50MP, f/1.8",
    ultrawideCamera: "12MP, f/2.2",
    telephotoCamera: null,
    frontCamera: "10MP, f/2.2",
    videoRecording: "4K@30fps",
    batteryCapacity: 4000,
    chargingSpeed: "25W wired, 15W wireless",
    wirelessCharging: true,
    network: "GSM / HSPA / LTE / 5G",
    wifi: "Wi-Fi 6E",
    bluetooth: "5.3",
    nfc: true,
    usb: "USB Type-C 3.2",
    fiveG: true,
    dimensions: "165.1 x 71.9 x 6.9 mm (unfolded)",
    weight: 187,
    rating: 4.4,
  },
];

async function main() {
  console.log(`Seeding ${phones.length} phones...`);

  for (const phone of phones) {
    await prisma.phone.upsert({
      where: { slug: phone.slug },
      update: phone,
      create: phone,
    });
  }

  const count = await prisma.phone.count();
  console.log(`Seed complete. Total phones in database: ${count}`);
}

main()
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
